set(_CATKIN_CURRENT_PACKAGE "maskor_ev3_gazebo")
set(maskor_ev3_gazebo_VERSION "0.0.0")
set(maskor_ev3_gazebo_MAINTAINER "dennis <dennis@todo.todo>")
set(maskor_ev3_gazebo_PACKAGE_FORMAT "1")
set(maskor_ev3_gazebo_BUILD_DEPENDS "roscpp")
set(maskor_ev3_gazebo_BUILD_EXPORT_DEPENDS "roscpp")
set(maskor_ev3_gazebo_BUILDTOOL_DEPENDS "catkin")
set(maskor_ev3_gazebo_BUILDTOOL_EXPORT_DEPENDS )
set(maskor_ev3_gazebo_EXEC_DEPENDS "roscpp")
set(maskor_ev3_gazebo_RUN_DEPENDS "roscpp")
set(maskor_ev3_gazebo_TEST_DEPENDS )
set(maskor_ev3_gazebo_DOC_DEPENDS )
set(maskor_ev3_gazebo_DEPRECATED "")